import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import html2canvas from "html2canvas";

/* ================= LOAD IMAGE ================= */

async function loadImageAsBase64(url) {
  try {
    if (!url) return null;

    const response = await fetch(url);

    if (!response.ok) {
      return null;
    }

    const blob = await response.blob();

    return await new Promise((resolve) => {
      const reader = new FileReader();

      reader.onloadend = () => {
        resolve(reader.result);
      };

      reader.readAsDataURL(blob);
    });
  } catch (err) {
    console.error(err);
    return null;
  }
}

/* ================= PDF ================= */

export async function generateDutySlip(
  dutySlip,
  trip,
  garageData
) {
  const doc = new jsPDF("p", "mm", "a4");

  /* ================= TITLE ================= */

  doc.setFontSize(17);

  doc.text("OFFICIAL DUTY SLIP", 105, 15, {
    align: "center",
  });

  doc.setFontSize(9);

  /* ================= TOTAL KM ================= */

  const totalKm =
    trip.startKm && trip.endKm
      ? (trip.endKm - trip.startKm).toFixed(2)
      : 0;

  /* ================= DETAILS TABLE ================= */

  autoTable(doc, {
    startY: 25,
    theme: "grid",
    body: [
      [
        "Trip ID",
        trip.tripId || "-",
        "Vehicle",
        trip.vehicleType || "-",
      ],

      [
        "Start Location",
        trip.startLocation ||
          trip.pickupLocation ||
          "-",
        "Start KM",
        trip.startKm || "-",
      ],

      [
        "End Location",
        trip.endLocation ||
          trip.dropLocation ||
          "-",
        "End KM",
        trip.endKm || "-",
      ],

      [
        "Driver",
        trip.driverName || "-",
        "Phone",
        trip.driverPhone || "-",
      ],

      [
        "Passenger",
        trip.userName || "-",
        "Phone",
        trip.userPhone || "-",
      ],

      [
        "Vehicle No",
        trip.driverCarNumber || "-",
        "Distance",
        `${totalKm} KM`,
      ],

      [
        "Amount",
        `₹ ${trip.totalAmount || 0}`,
        "Status",
        trip.status?.replace("_", " ") || "-",
      ],
    ],
  });

  /* ================= ROUTE MAP ================= */

  const mapElement =
    document.getElementById("trip-route-map");

  if (mapElement) {
    try {
      doc.setFontSize(12);

      doc.text(
        "Trip Route Map",
        14,
        doc.lastAutoTable.finalY + 10
      );

      const canvas = await html2canvas(
        mapElement,
        {
          useCORS: true,
          allowTaint: true,
          scale: 2,
        }
      );

      const mapImage =
        canvas.toDataURL("image/png");

      doc.addImage(
        mapImage,
        "PNG",
        14,
        doc.lastAutoTable.finalY + 15,
        180,
        70
      );
    } catch (err) {
      console.error(
        "Map screenshot failed",
        err
      );
    }
  }

  /* ================= GARAGE TABLE ================= */

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 90,
    theme: "grid",
    head: [["Garage Type", "KM", "Time"]],
    body: garageData.map((g) => [
      g.type,
      g.km || "-",
      g.time || "-",
    ]),
  });

  /* ================= SIGNATURE ================= */

  const signY = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(12);

  doc.text("Customer Signature", 14, signY);

  doc.setFontSize(9);

  doc.text(
    `Customer Name: ${
      trip.userName || "-"
    }`,
    14,
    signY + 8
  );

  doc.text(
    `Customer Phone: ${
      trip.userPhone || "-"
    }`,
    14,
    signY + 14
  );

  const signature =
    await loadImageAsBase64(
      trip.signatureUrl
    );

  if (signature) {
    doc.addImage(
      signature,
      "PNG",
      14,
      signY + 18,
      60,
      30
    );
  } else {
    doc.text(
      "Signature unavailable",
      14,
      signY + 28
    );
  }

  /* ================= FOOTER ================= */

  doc.text(
    "Generated by Arcot Cabs",
    105,
    285,
    {
      align: "center",
    }
  );

  /* ================= SAVE ================= */

  doc.save(`DutySlip-${trip.tripId}.pdf`);
}
