import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/* ================= LOAD IMAGE ================= */

async function loadImageAsBase64(url) {
  try {
    if (!url) return null;

    const response = await fetch(url, {
      mode: "cors",
    });

    if (!response.ok) {
      console.error("Image fetch failed:", response.status);
      return null;
    }

    const blob = await response.blob();

    return await new Promise((resolve) => {
      const reader = new FileReader();

      reader.onloadend = () => {
        resolve(reader.result);
      };

      reader.readAsDataURL(blob);
    });
  } catch (err) {
    console.error("Error loading image:", err);
    return null;
  }
}

/* ================= PDF ================= */

export async function generateDutySlip(
  dutySlip,
  trip,
  garageData
) {
  const doc = new jsPDF("p", "mm", "a4");

  /* ================= TITLE ================= */

  doc.setFontSize(17);
  doc.text("OFFICIAL DUTY SLIP", 105, 15, {
    align: "center",
  });

  doc.setFontSize(9);

  /* ================= TOTAL KM ================= */

  const totalKm =
    trip.startKm && trip.endKm
      ? (trip.endKm - trip.startKm).toFixed(2)
      : 0;

  /* ================= MAIN DETAILS ================= */

  autoTable(doc, {
    startY: 25,
    theme: "grid",
    styles: {
      fontSize: 9,
    },
    body: [
      [
        "Trip ID",
        trip.tripId || "-",
        "Vehicle",
        trip.vehicleType || "-",
      ],

      [
        "Start Location",
        trip.startLocation ||
          trip.pickupLocation ||
          "-",
        "Start KM",
        trip.startKm || "-",
      ],

      [
        "End Location",
        trip.endLocation ||
          trip.dropLocation ||
          "-",
        "End KM",
        trip.endKm || "-",
      ],

      [
        "Driver",
        trip.driverName || "-",
        "Phone",
        trip.driverPhone || "-",
      ],

      [
        "Customer",
        trip.userName || "-",
        "Phone",
        trip.userPhone || "-",
      ],

      [
        "Vehicle No",
        trip.driverCarNumber || "-",
        "Distance",
        `${totalKm} KM`,
      ],

      [
        "Total Amount",
        `₹ ${trip.totalAmount || 0}`,
        "Status",
        trip.status?.replace("_", " ") || "-",
      ],
    ],
  });

  /* ================= MAP SECTION ================= */

  const mapY = doc.lastAutoTable.finalY + 12;

  doc.setFontSize(12);
  doc.text("Trip Route", 14, mapY);

  const origin =
    trip.pickupLocation ||
    trip.startLocation ||
    "";

  const destination =
    trip.dropLocation ||
    trip.endLocation ||
    "";

  const googleMapLink = `https://www.google.com/maps/dir/${encodeURIComponent(
    origin
  )}/${encodeURIComponent(destination)}`;

  doc.setFontSize(9);

  doc.text("Pickup:", 14, mapY + 8);
  doc.text(origin || "-", 35, mapY + 8);

  doc.text("Drop:", 14, mapY + 15);
  doc.text(destination || "-", 35, mapY + 15);

  doc.setTextColor(0, 0, 255);

  doc.textWithLink(
    "Open Route In Google Maps",
    14,
    mapY + 25,
    {
      url: googleMapLink,
    }
  );

  doc.setTextColor(0, 0, 0);

  /* ================= GARAGE TABLE ================= */

  autoTable(doc, {
    startY: mapY + 35,
    theme: "grid",
    head: [["Garage Type", "KM", "Time"]],
    body: garageData.map((g) => [
      g.type,
      g.km || "-",
      g.time || "-",
    ]),
  });

  /* ================= SIGNATURE ================= */

  const signY = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(12);
  doc.text("Customer Signature", 14, signY);

  doc.setFontSize(9);

  doc.text(
    `Customer Name: ${
      trip.userName || "-"
    }`,
    14,
    signY + 8
  );

  doc.text(
    `Customer Phone: ${
      trip.userPhone || "-"
    }`,
    14,
    signY + 14
  );

  const signatureBase64 =
    await loadImageAsBase64(
      trip.signatureUrl
    );

  if (signatureBase64) {
    doc.addImage(
      signatureBase64,
      "PNG",
      14,
      signY + 18,
      60,
      30
    );
  } else {
    doc.text(
      "Signature unavailable",
      14,
      signY + 28
    );
  }

  /* ================= FOOTER ================= */

  doc.setFontSize(10);

  doc.text(
    "Generated by Arcot Cabs",
    105,
    285,
    {
      align: "center",
    }
  );

  /* ================= SAVE ================= */

  doc.save(`DutySlip-${trip.tripId}.pdf`);
}
